### PR TITLE
[ADD] crm_industry: Establish link on crm lead to res.partner.industry

### PR DESCRIPTION
**Pull request by ghost**
With odoo v11 a new model has been introduced: res.partner.industry https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/res/res_partner.py#L818

this module adds the link to crm.lead similar to crm_sector module but stays within the standard of odoo since crm_sector depend on partner_sector (another oca module)

however, the model res.partner.sector is quite different since it has hierarchy and res.partner.industry has not

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why don't you use crm_sector?

**Comment by ghost** [comment]
to stay closer to odoo standard. it's a new model introduced with 11.0

**Comment by pedrobaeza** [comment]
OK, thanks for the information. It makes sense.

**Comment by ghost** [comment]
ok. :+1:  thanks for the input, next time will explain in the description :)

**Comment by gdgellatly** [comment]
Closing, user has gone, module already merged

**Pull request closed without merging**
