### PR TITLE
[DEL] unmaintained lettermgmt_hr

### PR DESCRIPTION
**Pull request by hbrunn**
This module does not even install and is unmaintained as per #10

### CODE REVIEW

**Comment by hbrunn** [comment]
travis fails because of pylint errors in newsletter

**Comment by yvaucher** [comment]
@bwrsandman @max3903 agreed on this? Or any plan to make it installable?

**Comment by yvaucher** [comment]
According to https://github.com/OCA/crm/issues/10#issuecomment-71084944

:+1:

**Comment by pedrobaeza** [comment]
I would put it on `__unported__` instead, an remove it in v8.

**Comment by hbrunn** [comment]
@pedrobaeza this module is new, so I don't really understand your proposal?

**Comment by pedrobaeza** [comment]
OK, I think I get it, this version is the 6.1 one, and you are going to rename it to lettermgmt. Doesn't it?

**Comment by bwrsandman** [comment]
:+1:

**Comment by yvaucher** [comment]
@pedrobaeza No this one extends `lettermgmt`

**Comment by pedrobaeza** [comment]
And the source is from 6.1? If so, this should be moved to `__unported__`, not removed.

**Comment by bwrsandman** [comment]
@pedrobaeza If I recall correctly, lettermgmt from 6.1 wasn't an OCA module and a lot of cleaning was needed to bring it to our standards. At this point, the old 6.1 lettermgmt would need to be in `__unported__` for 6.1 and that makes no sense.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation.

**Pull request merged**
