### PR TITLE
[17.0][MIG] crm_industry: Migration to 17.0

### PR DESCRIPTION
**Pull request by mmrondon**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check CI

**Comment by mcassuto** [comment]
@mmrondon could you complete this merge ?

**Review by victoralmau — COMMENTED** [review]
Code review OK

**Review by victoralmau — APPROVED** [review]
Code review OK

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
