### PR TITLE
[16.0][MIG] crm_lead_code: Migration to 16.0

### PR DESCRIPTION
**Pull request by jaenbox**
Standard migration to 16.0

### CODE REVIEW

**Comment by rafaelbn** [comment]
Please review

imagen


imagen


Would you like to review @newtratip @HaraldPanten ? 😄 

Thank you for this contribution! ❤️

**Comment by jaenbox** [comment]
I have added a space in the kanban view. In the form view, the field code is offset because it is a readonly field.

**Review by rafaelbn — APPROVED** [review]
👍

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
