### PR TITLE
[MIG] crm_lead_vat: Migration to 14.0

### PR DESCRIPTION
**Pull request by redapureskill**
Migration of crm_lead_vat from V13 to **V14** :+1:

### CODE REVIEW

**Comment by redapureskill** [comment]
What's the problem 🤔, the checkes was successfull 28 hours ago.

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by fshah-initos — APPROVED** [review]
LGTM.

**Comment by fshah-initos** [comment]
Please squash last commits.

**Comment by redapureskill** [comment]
HELP

**Review by simahawk — CHANGES_REQUESTED** [review]
Tests are :red_circle:  here https://travis-ci.com/github/OCA/crm/jobs/496648085#L1187

It seems to be red on 14.0 for the same reason https://travis-ci.com/github/OCA/crm/jobs/482424388#L1065

So, please, fix 14.0 first in another PR :pray:

**Comment by oihane** [comment]
Problem with travis fixed in #388 please @redapureskill check it out

**Comment by fshah-initos** [comment]
@redapureskill can you please fix the Travis?

**Comment by fshah-initos** [comment]
Hi @redapureskill can you please fix the Travis so that we can merge this PR soon.

**Comment by fshah-initos** [comment]
Hi @redapureskill  can you please fix the Travis so that we can merge this PR soon.

**Comment by fshah-initos** [comment]
Hi @redapureskill  can you please fix the Travis so that we can merge this PR soon.

**Comment by fshah-initos** [comment]
Hi @redapureskill can you please fix the Travis so that we can merge this PR soon.

**Comment by redapureskill** [comment]
> Hi @redapureskill can you please fix the Travis so that we can merge this PR soon.

done

**Comment by fshah-initos** [comment]
@OCA/crm-sales-marketing-maintainers  Can you please merge this PR?

**Pull request merged**
