### PR TITLE
Add field to opportunities form too.

### PR DESCRIPTION
**Pull request by yajo**
CC @rafaelbn @carlos-incaser @sergio-incaser @pedrobaeza.

### CODE REVIEW

**Comment by carlosdauden** [comment]
:+1:

**Comment by janetrp** [comment]
question: TIN in spanish should be CIF? Tested in Runbot.
VAT field (TIN) appears also in opportunities
:+1:

**Comment by yajo** [comment]
Weird, Odoo does not generate the correct .pot file and I cannot translate! :fearful: What to do?

**Comment by rafaelbn** [comment]
:+1:

**Pull request merged**
