### PR TITLE
[13.0][MIG] crm_lead_vat

### PR DESCRIPTION
**Pull request by newtratip**
Add vat in crm lead
Peek 2020-03-13 15-38

### CODE REVIEW

**Comment by newtratip** [comment]
Hello @oihane 
You were migration to v.12, Could you review this for minor change ?
Thank.

**Review by oihane — APPROVED** [review]
Without knowing how crm module is in v13.0 LGTM

**Review by skeller1 — APPROVED** [review]
Tested on Runbot and locally on  Odoo 13.0-20200417 (Community Edition) 

LGTM

**Comment by pedrobaeza** [comment]
Please rebase and you'll need to redo pre-commit stuff

**Comment by newtratip** [comment]
@pedrobaeza 
I rebase and redo pre-commit already. Could you merge this again ?

**Pull request merged**
