### PR TITLE
[ADD] New module <crm_claim_deadline_visible>

### PR DESCRIPTION
**Pull request by oihane**
Moved from https://github.com/avanzosc/odoo-addons

### CODE REVIEW

**Comment by anajuaristi** [comment]
For me, as project manager is incredibly usefull to see the claim dead-line directly on tree, so :+1: 

Tested and used in production environment

**Comment by pedrobaeza** [comment]
I see this very little for a module. I think it's better to propose this as OCB/Odoo patch.

**Comment by oihane** [comment]
@anajuaristi take a look in:
http://3111886-293-b569de.runbot1.odoo-community.org/web/login?redirect=http%3A%2F%2F3111886-293-b569de.runbot1.odoo-community.org%2Fweb%3Fdb%3D3111886-293-b569de-all

**Comment by qtheuret** [comment]
I'm agree with @pedrobaeza . Why don't propose a pull request on OCB/Odoo instead of a new module ?

**Comment by oihane** [comment]
@qtheuret it is already proposed.

**Comment by anajuaristi** [comment]
:+1: I think it should be on core so I agree to include it as a patch in OCB and propose to Odoo for next versions.

**Comment by oihane** [comment]
I'll close this PR, if anyone is interested in this module (because it is not approved yet in OCB/Odoo) it is available at https://github.com/avanzosc/odoo-addons

**Pull request closed without merging**
