### PR TITLE
[13.0][MIG] crm_lead_product

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
crm_lead_product migration to v13

cc ~ @ForgeFlow @LoisRForgeFlow @JordiBForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Tested on runbot :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
