### PR TITLE
[12.0] update dotfiles

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Review by antonioburic — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by hbrunn** [comment]
he ocabot?

/ocabot merge patch

**Comment by pedrobaeza** [comment]
`Error: Version 3.6 with arch x64 not found`

It seems this Python version has gone out during last days.

**Comment by hbrunn** [comment]
hmmm. So we'll have to discuss OCA-wide how to handle this. I run several 12.0 instances with python 3.10 and https://github.com/OCA/OCB/pull/1037, will propose doing this on the mailinglist

**Comment by hbrunn** [comment]
wait, https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json claims we have that version, just not for `ubuntu-latest`, as that's 22.04 now https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

**Comment by hbrunn** [comment]
if this works, I'll PR that change to the repo template so that the others can just do a copier update

**Comment by pedrobaeza** [comment]
This is similar to this conversation: https://github.com/OCA/oca-addons-repo-template/issues/174

**Comment by hbrunn** [comment]
ah, Stephane already predicted that. good, PR follows suit

**Comment by pedrobaeza** [comment]
The pre-commit job doesn't start...

I'm launching anyway the merge command to not wait:

/ocabot merge patch

**Comment by hbrunn** [comment]
thanks, I've just opened https://github.com/OCA/oca-addons-repo-template/pull/181

**Comment by rousseldenis** [comment]
@hbrunn Remember that !fixup commits won't be squashed with ocabot merge

**Comment by hbrunn** [comment]
thanks, indeed I should have squashed first. Making ocabot squash is on my list though, so sooner or later that will happen :-)

**Pull request merged**
