### PR TITLE
[MIG] crm:lettermgmt Migrated Module to V9.

### PR DESCRIPTION
**Pull request by HardikG**

### CODE REVIEW

**Comment by hbrunn** [comment]
did you have a look at https://github.com/OCA/crm/pull/87 ? There's only a few things to do before this can be merged, so I think it might be wise to start with this for the 9 port.
@ivantodorovich any input on this one?

**Comment by HardikG** [comment]
@hbrunn Thank you for reviewing this. Yes I have read now #87 . But can you tell me exact points that I need to work on ?

**Comment by HardikG** [comment]
@hbrunn , I have changed from "class" to "category", Improved UI, removed created and approved state.

**Comment by rafaelbn** [comment]
This PR includes more than one module at once. Please make 1 PR per module. Thanks

**Review by rafaelbn — CHANGES_REQUESTED** [review]
This PR must be closed and Opened  new ones with 1 PR 1 module. Thanks

**Comment by HardikG** [comment]
@rafaelbn : Thank you for reviewing this PR. After integrating the travis in my local for this repo. it was not allowing me to commit the code and it needs to fix the pep8 and flake errors from other modules. So I have fixed and mistakenly committed all the code. So Now I am closing this PR and creating new one as rafaelbn said (And Yes this time with only single module).

**Pull request closed without merging**
