### PR TITLE
[16.0][MIG] crm_location_nuts

### PR DESCRIPTION
**Pull request by edlopen**
Standard migration crm_location_nuts.

I've enabled the tests here as NUTs can be loaded now either by mocking the tests or by running the importer.

@moduon MT-1666

@yajo @EmilioPascual @Shide @fcvalgar @rafaelbn review this PR when you can. Thank you!

PS: I'tll make a video explaining briefly how it works 

https://www.loom.com/share/4330066558884039bde5adba3cae5399

### CODE REVIEW

**Review by EmilioPascual — APPROVED** [review]
Nice job @edlopen.
Functional and code review.

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, Thank you @edlopen 

image

image


image

**Review by yajo — APPROVED** [review]
Great!

**Pull request merged**
