### PR TITLE
[16.0][mig] crm_project_task

### PR DESCRIPTION
**Pull request by EmilioPascual**
Migration module. Allow create task from lead or opportunity.

@moduon MT-3175

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested in runboat 👍🏼 

https://www.loom.com/share/199578aabf9a4a04a19bd2fb1960761c?sid=b0a85f84-a072-413a-94ae-05cf6414f61d

**Review by fcvalgar — APPROVED** [review]
Functonal review.

LGTM, thank you @EmilioPascual

**Pull request merged**
