### PR TITLE
[ADD] New module <crm_lead_code>

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by anajuaristi** [comment]
:+1:

**Comment by max3903** [comment]
Tested on runbot.
:+1:

**Comment by ameyioli** [comment]
:+1:

**Comment by anajuaristi** [comment]
So this module obtained 3 :+1:  --> Someone in OCA with credentials could merge it? 

Thank you!!
Ana

**Comment by oihane** [comment]
Required by @anajuaristi I made visible `code` in opportunities.

**Comment by oihane** [comment]
Thanks @max3903

**Pull request merged**
