### PR TITLE
[14.0][MIG] crm_claim_type: Migration to 14.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration.
T-6301

### CODE REVIEW

**Review by Jaimermaccione — APPROVED** [review]
LGTM! Functional review on runboat.

@RogerSans

**Comment by angelgarciadelachica** [comment]
@RogerSans Can you change the name of the second commit? It should not have the version. 
THX!

**Comment by RogerSans** [comment]
> @RogerSans Can you change the name of the second commit? It should not have the version. THX!

Done. THX

**Comment by angelgarciadelachica** [comment]
Technical review. LGTM 
@HaraldPanten Do you think you could merge it? THX

**Review by angelgarciadelachica — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
