### PR TITLE
[13.0][IMP] crm_claim: Remove unnecessary (and confusing) activity fields in views (form + tree).

### PR DESCRIPTION
**Pull request by victoralmau**
Remove unnecessary (and confusing) activity fields in views (form + tree).

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT38822

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
This repo branch needs update to get GH Actions CI

**Comment by victoralmau** [comment]
Repo updated and rebase done.

**Review by chienandalu — APPROVED** [review]
A little text with the rationale in the commit would be nice (it's a remanent from v8 implementation, blah, blah...)

**Review by pedrobaeza — APPROVED** [review]
Yes, please explain more in the commit message. Words are cheap!

**Comment by simahawk** [comment]
@victoralmau there's no need to write everything in one sentence. You shouldn't do it at all actually.
Keep it short and synthetic. The description goes 2 lines below :wink: 
```
[IMP] crm_claim: improve views

bla bla bla
```

**Comment by victoralmau** [comment]
Commit message updated.

**Comment by pedrobaeza** [comment]
Several points for your next message commit to be perfect :wink::

- Don't put a dot at the end of the first line.
- Leave an extra empty line between the first line and the next one.
- Limit length of each line to 80 cols.

**Pull request merged**
