### PR TITLE
[FIX] Replaced location_id field to avoid beign removed by the addres…

### PR DESCRIPTION
**Pull request by pablocm-aserti**
…s_format dynamic view formatting

### CODE REVIEW

**Comment by pablocm-aserti** [comment]
Fixes #59 replacing the field to the same place [base_location does](https://github.com/OCA/partner-contact/blob/094d7d7aec1d5c42f4833a94141f4cd317ab944f/base_location/views/partner_view.xml#L10) in the partner form

**Comment by pedrobaeza** [comment]
cc @JavierIniesta @antespi

**Comment by pedrobaeza** [comment]
@antespi, this is still pending. Can you please check it?

For me, :+1:

**Comment by rafaelbn** [comment]
I get this error when I go to: Sales - Leads

```
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3143000-60-f7d624/openerp/models.py", line 5863, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3143000-60-f7d624/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3143000-60-f7d624/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3143000-60-f7d624/openerp/addons/crm_location/models/crm_lead.py", line 49, in on_change_partner_id
    res = super(CrmLead, self).on_change_partner_id(partner_id)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3143000-60-f7d624/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
TypeError: 'NoneType' object is not callable
```

**Comment by rafaelbn** [comment]
This BUG has been fixed here: https://github.com/odoo/odoo/commit/906bf16a7617a86455547e3ebc08485cc80458df

**Comment by rafaelbn** [comment]
Hi @pablocm-aserti , I'm closing this PR as it's not needed. It was solved upstream. Make a comment if you consider it.

**Pull request closed without merging**
