### PR TITLE
[10.0][IMP][crm_phonecall] crm phonecall default values from marketing details

### PR DESCRIPTION
**Pull request by robyf70**
Pass marketing details as default values from lead/opportunity to phonecalls

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Good, would you mind adding a test for the change?

I guess you can just add some more assertions to https://github.com/OCA/crm/pull/176/files#diff-bfb57436a647f459fc8c33ec37276ce2R96

**Comment by rafaelbn** [comment]
Dear @robyf70 please could you review travis errors? It's red and we need all bots green :green_heart: before mergin. Thanks!

> continuous-integration/travis-ci/pr — The Travis CI build failed

**Comment by robyf70** [comment]
@rafaelbn Looks like travis got some errors:

```Creating instance:
createdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Using previous openerp_template database.
```

**Comment by NL66278** [comment]
Travis error can be resolved by changing .travis.yml in root of repo. addons part should look like this:
```
addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
```
The change is to add the postgres version.

**Comment by Yajo** [comment]
See #207

**Comment by yajo** [comment]
See #292

**Comment by yajo** [comment]
Rebase please, it will get travis working.

**Comment by rafaelbn** [comment]
@robyf70 please Rebase please, it will get travis working. :smile:

**Comment by robyf70** [comment]
@Yajo @rafaelbn Done :)!

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
