### PR TITLE
[FIX] greenify Runbot

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
There's still the warning about a non-existing field on a create/update operation dict.

**Comment by oihane** [comment]
@pedrobaeza fixed

**Comment by lmignon** [comment]
:+1:  Once travis is green.

**Comment by pedrobaeza** [comment]
As Travis is stuck and the greenify was on Runbot, I merge.

**Pull request merged**
