### PR TITLE
[16.0][MIG] crm_won_restrict_per_stage: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v16.

@Tecnativa
TT48707

@pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The pre-commit commit doesn't contain the module name.

**Comment by carolinafernandez-tecnativa** [comment]
> The pre-commit commit doesn't contain the module name.

done

**Review by pedrobaeza — APPROVED** [review]

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Pull request merged**
