### PR TITLE
[12.0][ADD] crm_klaviyo

### PR DESCRIPTION
**Pull request by hbrunn**
This module stores API keys for [Klaviyo](https://www.klaviyo.com) and exposes the [Klaviyo SDK](https://github.com/klaviyo/klaviyo-api-python) for other modules or automated actions to use.

Usage
=====

To use this module, you can ie create an automated action on partner creation,
filtered by the customer flag, and add code similar to the following:

    client = env['klaviyo.account'].get_api()
    client.Profiles.create_profile({
        'type': 'profile',
        'attributes': {
            # this assumes you have partner_firstname installed
            'first_name': record.firstname,
            'last_name': record.lastname,
            'email': record.email,
        }
    });

to push new partners to Klaviyo.

### CODE REVIEW

**Comment by hbrunn** [comment]
this needs to be rebased once https://github.com/OCA/crm/pull/458 is merged

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Travis still red

**Comment by hbrunn** [comment]
that won't change before https://github.com/OCA/crm/pull/458 is merged and this is rebased on the result :-(

**Review by MPishpecki — APPROVED** [review]

**Comment by MPishpecki** [comment]
I approve the code but Travis needs to pass somehow.

**Review by antonioburic — APPROVED** [review]

**Comment by hbrunn** [comment]
@MPishpecki greenness achieved

**Comment by MPishpecki** [comment]
Thank you for the PR @hbrunn

**Review by rafaelbn — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
