### PR TITLE
[17.0][MIG] crm_salesperson_planner: Migration to 17.0

### PR DESCRIPTION
**Pull request by BernatObrador**
Module migrated to version 17.0

cc https://github.com/APSL 158506

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @ppyczko  please review

Issue https://github.com/OCA/crm/issues/525

### CODE REVIEW

**Review by peluko00 — COMMENTED** [review]
image
The Salesperson Visits view don't see good.

**Review by peluko00 — APPROVED** [review]
LGTM

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat and works as intended

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Pull request merged**
