### PR TITLE
[15.0][FIX] crm_lead_firstname: missing contact_lastname when quick create is used

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Comment by bodedra** [comment]
@rven I have reviewed your PR and it's LG.

Minor correction: Would you please split your commit like:

1. [FIX] Update copier template
2. [FIX] Missing contact_lastname when quick create is used

OR submit two PRs separately.

**Comment by StefanRijnhart** [comment]
@rven That's `copier -f update` to update the dot files. I would suggest to split PRs.

**Comment by StefanRijnhart** [comment]
Pre-commit config was fixed in https://github.com/OCA/crm/pull/460. Please rebase.

**Review by StefanRijnhart — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Pull request merged**
