### PR TITLE
[10.0] [FIX] crm_claim: typo date default value

### PR DESCRIPTION
**Pull request by eicher31**
The attribute default of the field date is misspelled.

### CODE REVIEW

**Review by NL66278 — APPROVED** [review]
:+1: LGTM. Obvious fix...

**Review by ecino — APPROVED** [review]
Nice catch! This should be fast tracked in my opinion.

**Comment by pedrobaeza** [comment]
Please forward-port it to v11/v12

**Comment by eicher31** [comment]
:+1: Thanks

**Pull request merged**
