### PR TITLE
Add slovene translation

### PR DESCRIPTION
**Pull request by sysadminmatmoz**
Since this repository is not on Transifex yet I'm just adding the Slovene translation

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1: (technically)

**Comment by sysadminmatmoz** [comment]
Is there any chance to merge this? I understand the necessity for the review workflow, but here we're talking translations - if this repository was on transifex, I could do the same thing without reviews.

Thanks in advance.

**Comment by pedrobaeza** [comment]
You have to check your git technique, because it seems that you're using merge strategy against rebase, and this ends with unwanted commits.

**Comment by sysadminmatmoz** [comment]
Ok. Help me with that please. I usually do:
- git fetch upstream (to sync with the original repo)
- git rebase upstream/8.0
- git pull (to pull my own commits over it)
- git push (to push the synchronized version)

No git merge, but git pull actually makes a git merge. What am I doing wrong?

**Comment by pedrobaeza** [comment]
Usual git flow is:
- Create a specific branch for your changes: `git checkout -b branch_name`
- Commit your changes there. (`git commit...`)
- Push the branch to your forked repo (`git push sysadminmatmoz branch_name`). In this point, you're creating a new branch on your forked repository, not using 8.0, which is the convenient way of working.
- If there are changes on the main branch, then do `git rebase origin/8.0` (or upstream if you name it that way the remote). The important thing here is that you make it  **over your branch**. You already have the changes on it. You're are only rebasing to get the changes from upstream.
- Force push your branch to get it on the remote.

So, you can deduce that the thing that mesess up all is the git pull operation that you make.

**Comment by sysadminmatmoz** [comment]
Got it, thanks. It's the force of habit - doing it that way for years. I'm using the 8.0 branch (on my fork) because my fork is actually my production repo, in fact I start a PR only after I've been using a change of mine on all my instances for some time. That's why I keep all my forks always up to date with the origins.

I'll try to change my ways :smile:

**Pull request closed without merging**
