### PR TITLE
[15.0][IMP][crm_lead_vat] Sync vat between partner and lead

### PR DESCRIPTION
**Pull request by EmilioPascual**
- Add behavior to sync vat between partner and lead.

@moduon MT-3130 @rafaelbn

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Wonderful!

Tested in runboat! 👍🏼 

https://www.loom.com/share/5d87d4dd7dbd4380aed64bfd68070184?sid=9065f0cb-b1cd-45a8-9767-fdb164399506

**Comment by rafaelbn** [comment]
Discovered a FIX for propagating the VAT to the commercial partner id

**Comment by EmilioPascual** [comment]
> Discovered a FIX for propagating the VAT to the commercial partner id

Fix it

https://www.loom.com/share/7e93f0bca41f40eba7cf0e0f42864b23?sid=3fd72985-39e2-4be4-bb11-15ce4a4ead84

Try now, please

**Review by fcvalgar — APPROVED** [review]
LGTM, Thank you @EmilioPascual

**Pull request merged**
