### PR TITLE
[17.0][MIG] crm_claim: Migration to 17.0

### PR DESCRIPTION
**Pull request by BernatObrador**
Module migrated to version 17.0

cc https://github.com/APSL 159308

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @ppyczko please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check CI

**Review by mpascuall — APPROVED** [review]
LGTM

**Comment by peluko00** [comment]
Squash administrive commits please @BernatObrador

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Comment by BernatObrador** [comment]
@pedrobaeza Sorry for pinging you directly, is this ready to merge?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration crm_claim
/ocabot merge nobump

**Pull request merged**
