### PR TITLE
14.0 mig crm lead firstname

### PR DESCRIPTION
**Pull request by redapureskill**
Migrating crm_lead_firstname from 13 to **14** :+1:

### CODE REVIEW

**Comment by redapureskill** [comment]
@tonygalmiche you can check this one too if you want 😇

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Review by benbrich — APPROVED** [review]
I have just done a functional review as demo user on runbot. Everything runs smoothly, thanks for the effort!

**Review by HaraldPanten — APPROVED** [review]

**Review by newtratip — APPROVED** [review]
:+1: LGTM

**Pull request merged**
