### PR TITLE
[MIG][15.0]crm_lead_firstname: Migration 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
No idea about the pre-commit fail. this might be a bug from pre-commit, not sure. can anyone assist?

**Review by ajaniszewska-dev — APPROVED** [review]
code LG

**Comment by houssine78** [comment]
@bizzappdev  could this be reopened ?

**Comment by houssine78** [comment]
@rafaelbn any way that you could reopen this PR ?

**Comment by XanderDeMatteis** [comment]
fixed in https://github.com/OCA/crm/pull/441

**Pull request closed without merging**
