### PR TITLE
[ADD] crm_deduplicate_by_ref

### PR DESCRIPTION
**Pull request by pedrobaeza**
Deduplicate Contacts by reference
=================================

This module extends the criteria to match duplicated contacts using the field reference.

Usage
=====

To use this module, you need to:

* Go to *Sales > Tools > Deduplicate Contacts*.
* Mark "Reference" in the section "Search duplicates based on duplicated data in".
* This criteria will be used for deduplicating.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @tecnativa @cubells

**Review by carlosdauden — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Tested functionally

**Review by cubells — APPROVED** [review]
Perfect for me.
Tested

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Pull request merged**
