### PR TITLE
[IMP] Add smartbutton to leads and opportunities

### PR DESCRIPTION
**Pull request by cubells**
Usability increase if smart button is added to leads and pipelines.

cc @Tecnativa

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
Tested functionally in runbot , thanks!

**Comment by chienandalu** [comment]
Wouldn't it be better if the smart button had this behaviour?:

- 0-1 calls: goes to call form view (so you either schedule or register or, at least, save one click :D)
- >1 calls: goes to calls tree view as it does now.

And maybe not the focus of this PR: 

- Wouldn't it be better if Scheduled Calls menu would be available to all users by default? It's like a hidden feature until you realise that you have to enable permissions in the user's prefs.

- Form view available in both Logged calls and Scheduled calls view would improve the flow (i.e. if you hold a call by mistake it's hard to recover it to another one. This form view is only accesible form the calendar view and then clicking in the call in Logged calls view.

**Review by luismontalba — APPROVED** [review]
Functionality tested

**Review by chienandalu — APPROVED** [review]
Sorry, my last comment didn't go here. This is aproved

**Pull request merged**
