### PR TITLE
[16.0][MIG] crm_project: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard Migration V16
- Rename module crm_lead_to_task (crm_project in old versions)

@Tecnativa

TT45226

@pedrobaeza 

P.D: Close this PR https://github.com/OCA/crm/pull/495

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional Review,

LGTM, Thank you @carolinafernandez-tecnativa 

image

image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
