### PR TITLE
[MIG] crm_lead_firstname: Migration to 15.0

### PR DESCRIPTION
**Pull request by XanderDeMatteis**

### CODE REVIEW

**Review by rconjour — APPROVED** [review]
LGTM

**Comment by StefanRijnhart** [comment]
Thanks! Please squash your two migration commits.
Oh, you may also squash all the old `migration to 14.0` commits.
image

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@XanderDeMatteis was going to check if this could be merged, and I noticed the conflict. Can you rebase please?

**Comment by StefanRijnhart** [comment]
@XanderDeMatteis thanks for the rebase!

**Pull request merged**
