### PR TITLE
[12.0][IMP] crm_phonecall UI Phonecall button next to Meetings

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Review by agyamuta — APPROVED** [review]
It looks good to me.

**Comment by dreispt** [comment]
image

**Comment by dreispt** [comment]
image

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Change the inherit of `base.view_partner_form` to `crm.view_partners_form_crm1`

**Comment by dreispt** [comment]
@pedrobaeza fixed!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
