### PR TITLE
8.0 mig mail thread track x2many

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be in OCA/social instead, and there's already a module proposed for this for v11: https://github.com/OCA/social/pull/254

**Comment by hbrunn** [comment]
@pedrobaeza agreed with the repo, but this does something totally different than you think

**Comment by hbrunn** [comment]
actually, this might better be a candidate for server-tools or server-backend

**Comment by hbrunn** [comment]
@daramousk it helps when you paste the relevant parts of the readme in the first comment

**Pull request closed without merging**
