### PR TITLE
[13.0][MIG] crm_claim_code: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT27101

Supersede https://github.com/OCA/crm/pull/313

### CODE REVIEW

**Comment by ernestotejeda** [comment]
@mamcode could you review, please?

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
