### PR TITLE
[ADD] - Add archive action to crm stage

### PR DESCRIPTION
**Pull request by sbejaoui**
This addon add archive action to crm stages.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be `crm_stage_active` following other examples like https://github.com/OCA/partner-contact/tree/12.0/partner_bank_active?

**Comment by sbejaoui** [comment]
> Shouldn't this be `crm_stage_active` following other examples like https://github.com/OCA/partner-contact/tree/12.0/partner_bank_active?

yes, I do that

**Comment by sbejaoui** [comment]
cc/ @gva-acsone

**Comment by simahawk** [comment]
FTR we've tried to propose this change to core https://github.com/odoo/odoo/pull/32518

**Pull request closed without merging**
