### PR TITLE
[15.0][mig] crm_lead_code

### PR DESCRIPTION
**Pull request by santostelmo**
Migrating crm_lead_code

### CODE REVIEW

**Review by SilvioC2C — APPROVED** [review]
LGTM

**Review by yankinmax — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by cvinh** [comment]
please check https://github.com/OCA/crm/pull/405

**Comment by santostelmo** [comment]
> please check #405



> please check #405

Make sense I test it

**Comment by santostelmo** [comment]
@cvinh added https://github.com/OCA/crm/pull/405

**Comment by santostelmo** [comment]
@cvinh I checked https://github.com/OCA/crm/pull/405. But since there is changes requested on this PR I am not including it here for the moment.

**Pull request merged**
