### PR TITLE
[IMP][13.0] crm_phonecall: improvement for inheritance

### PR DESCRIPTION
**Pull request by ValentinVinagre**
This improvement makes this module more inheritable. 
It's is needed to have an easier/clean code in crm_phonecall_summary_predefined -> https://github.com/OCA/crm/pull/324

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten and @skeller1 could you review ?
Thanks,

**Review by HaraldPanten — APPROVED** [review]
Functional review. 👍

**Review by skeller1 — APPROVED** [review]

**Comment by rousseldenis** [comment]
Great. @ValentinVinagre Is this ready ?

**Comment by ValentinVinagre** [comment]
Hi @rousseldenis , yes it's ready to merge if it's fine.

**Pull request merged**
