### PR TITLE
[14.0][MIG] crm_claim: Migration to 14.0

### PR DESCRIPTION
**Pull request by Daniel-CA**

### CODE REVIEW

**Comment by Daniel-CA** [comment]
superseded  #370

**Review by dsolanki-initos — APPROVED** [review]
LGTM.

**Comment by redapureskill** [comment]
> LGTM.

#370  is fixed, LGTM it

**Comment by pedrobaeza** [comment]
@Daniel-CA remember to name the PR title correctly (I have done it for you this time).

**Comment by Daniel-CA** [comment]
> @Daniel-CA remember to name the PR title correctly (I have done it for you this time).

Thanks @pedrobaeza

**Review by oihane — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
It would be great if we could merge this PR.

**Pull request merged**
