### PR TITLE
[13.0][MIG] crm_industry: Migration to 13.0

### PR DESCRIPTION
**Pull request by skeller1**
**Standard Migration of crm_industry to 13.0**

Depends on https://github.com/OCA/partner-contact/pull/916

### CODE REVIEW

**Review by mamcode — APPROVED** [review]
LGTM, travis is not passing but I can't see the logs (the server is showing error 404), locally I see that pre-commit is passing, the unit test is passing and functionally is all right. 
Thanks for this migration.

**Comment by mamcode** [comment]
Maybe you can squash the commits of translations to make commit history look better.

**Comment by skeller1** [comment]
> LGTM, travis is not passing but I can't see the logs (the server is showing error 404), locally I see that pre-commit is passing, the unit test is passing and functionally is all right.
> Thanks for this migration.



> LGTM, travis is not passing but I can't see the logs (the server is showing error 404), locally I see that pre-commit is passing, the unit test is passing and functionally is all right.
> Thanks for this migration.
This addon depends on partner_industry_secondary addon. MR has been merged in partner-contact repo.
Did Push Force and pipe is running now. We will see.
Thank you

**Review by HaraldPanten — APPROVED** [review]
Seems to be OK

**Pull request merged**
