### PR TITLE
[FIX] Category group_by in phonecall search view

### PR DESCRIPTION
**Pull request by diggy128**

### CODE REVIEW

**Comment by yajo** [comment]
This should be fixed upstream, did you try?

**Comment by diggy128** [comment]
But the fix has to do with the OCA module (The fact that the whole module should be merged upstream is another issue).

**Review by pedrobaeza — APPROVED** [review]

**Comment by diggy128** [comment]
It seems I've messed up.
I wanted to create a new pull request, but somehow I've attached it to this one.
Is there any way to revert this?

Sorry for the inconvenience, Git newbie.

**Comment by yajo** [comment]
Yeah, don't worry, Git is a hard tool to learn 😉:

```
git checkout $the_branch_that_points_to_this_pr
git reset --hard $correct_commit_sha_for_this_pr
git push --force
```

**Comment by diggy128** [comment]
@Yajo Seems to be OK now. Thanks for the invaluable tips. I will try to learn from my mistakes and be more careful next time.

**Review by yajo — APPROVED** [review]

**Pull request merged**
