### PR TITLE
[11.0] fix crm_claim import

### PR DESCRIPTION
**Pull request by igallart**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@igallart again I don't understand how do you have your environment for having troubles with that import. This is not a problem of the module, but of your environment. I advise you to check it because this "fix" is only something for covering the real problem.

**Comment by igallart** [comment]
@pedrobaeza, this change is the same that https://github.com/OCA/crm/pull/186

**Comment by pedrobaeza** [comment]
I know, and I insist that the problem is not in code...

**Comment by igallart** [comment]
Thanks @pedrobaeza, I will review my installation

**Comment by igallart** [comment]
@pedrobaeza, tenías razón, los repositorios estaban en orden incorrecto, tenía crm antes que los nativos de Odoo, y no me cargaba los imports. Lo cierro.

Gracias.

**Comment by SalahAdDin** [comment]
@igallart, no entiendo, donde los tenías? como configuras eso?

**Comment by igallart** [comment]
@SalahAdDin, los pusimos antes de los addons de Odoo y nos daba error, entonces para que funcionase los pusimos a continuación de esos y ya nos iba. No hemos vuelto a tener más versiones 11 para probar, en cuanto tenga la ocasión los pondremos antes de los addons de Odoo a ver si ya nos carga.

**Comment by pedrobaeza** [comment]
Please, English only in these international repositories

**Comment by SalahAdDin** [comment]
@igallart Ok, but, where are you putting them? i just touched the config file, no more, nothing inside `odoo`.

**Comment by SalahAdDin** [comment]
So, i don't understand how you handle the addons order.

**Comment by igallart** [comment]
Hi, I had crm, addons-odoo and it failed, and after change to addons-odoo,crm and it worked.

**Comment by SalahAdDin** [comment]
@igallart , but where?
This is my config file:
```conf
[options]
addons_path = /mnt/extra-addons, /var/lib/odoo/addons/11.0/account-analytic, /var/lib/odoo/addons/11.0/account-financial-tools, /var/lib/odoo/addons/11.0/account-invoicing, /var/lib/odoo/addons/11.0/community-data-files, /var/lib/odoo/addons/11.0/currency, /var/lib/odoo/addons/11.0/hr, /var/lib/odoo/addons/11.0/knowledge, /var/lib/odoo/addons/11.0/management-system, /var/lib/odoo/addons/11.0/manufacture, /var/lib/odoo/addons/11.0/manufacture-reporting, /var/lib/odoo/addons/11.0/mis-builder, /var/lib/odoo/addons/11.0/partner-contact, /var/lib/odoo/addons/11.0/product-attribute, /var/lib/odoo/addons/11.0/project, /var/lib/odoo/addons/11.0/purchase-workflow, /var/lib/odoo/addons/11.0/reporting-engine, /var/lib/odoo/addons/11.0/server-auth, /var/lib/odoo/addons/11.0/server-ux, /var/lib/odoo/addons/11.0/web, /var/lib/odoo/addons/11.0/backend_theme, /var/lib/odoo/addons/11.0/SerpentCS_Contributions 
data_dir = /var/lib/odoo
admin_passwd = J5VcCfBuq/RomXsaHwNZ7lF9/7qxcmnj
; csv_internal_sep = ,
; db_maxconn = 64
; db_name = rotafilo
; db_template = template1
dbfilter = ^rotafilo.*$
; debug_mode = True
; email_from = False
limit_memory_hard = 1677721600
limit_memory_soft = 805306368
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
; list_db = False
load-language=en_GB, tr, es_CO
; log_db = False
log_handler = [':WARNING','werkzeug:CRITICAL','odoo.service.server:INFO']
log_level = warn
logfile = /var/log/odoo/openerp-server.log
logrotate = True
longpolling_port = 8072
max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
proxy_mode = True
smtp_password = odoo2018
smtp_port = 465
smtp_server = smtp.yandex.com
smtp_ssl = True
smtp_user = erp@rotafilo.com
timezone = Europe/Istanbul
workers = 6
without_demo = True
; xmlrpc = True
; xmlrpc_interface =
; xmlrpc_port = 8069
; xmlrpcs = True
; xmlrpcs_interface =
; xmlrpcs_port = 8071
```

I don't touch any other thing, I'm using a `Docker` image based in the official one.
I'm testing it with **_Odoo 11._**

**Comment by SalahAdDin** [comment]
@igallart

**Comment by igallart** [comment]
@SalahAdDin:

addons_path = /opt/odoo/odoo110/src/crm,/opt/odoo/odoo110/src/core/addons

**Comment by SalahAdDin** [comment]
I'm crazy right now, does not `odoo` load its addons before the extra module path's addons?

**Comment by SalahAdDin** [comment]
I did review this and yes, you are right:
`addons_path = /usr/lib/python3/dist-packages/odoo/addons/, /mnt/extra-addons, /var/lib/odoo/addons/11.0/account-analytic, /var/lib/odoo/addons/11.0/account-financial-tools, /var/lib/odoo/addons/11.0/account-invoicing, /var/lib/odoo/addons/11.0/community-data-files, /var/lib/odoo/addons/11.0/crm, /var/lib/odoo/addons/11.0/currency, /var/lib/odoo/addons/11.0/hr, /var/lib/odoo/addons/11.0/knowledge, /var/lib/odoo/addons/11.0/management-system, /var/lib/odoo/addons/11.0/manufacture, /var/lib/odoo/addons/11.0/manufacture-reporting, /var/lib/odoo/addons/11.0/mis-builder, /var/lib/odoo/addons/11.0/muk_base, /var/lib/odoo/addons/11.0/muk_dms, /var/lib/odoo/addons/11.0/muk_web, /var/lib/odoo/addons/11.0/partner-contact, /var/lib/odoo/addons/11.0/product-attribute, /var/lib/odoo/addons/11.0/project, /var/lib/odoo/addons/11.0/purchase-workflow, /var/lib/odoo/addons/11.0/reporting-engine, /var/lib/odoo/addons/11.0/server-auth, /var/lib/odoo/addons/11.0/server-ux, /var/lib/odoo/addons/11.0/web, /var/lib/odoo/addons/11.0/backend_theme, /var/lib/odoo/addons/11.0/SerpentCS_Contributions 
`
But i think it is not a correct way to solve this issue, because it does happen only with `crm` module.
Why?

**Comment by pedrobaeza** [comment]
Yes, it is.

**Comment by SalahAdDin** [comment]
But it is not a clean solution, i mean, i just get out `crm` module path and i haven't problem, why?
I'm running a `Docker` container with `Odoo` `debian` installed.

**Comment by pedrobaeza** [comment]
No, it's mandatory to load first odoo addons path. It's Python requirement.

**Comment by igallart** [comment]
I think that @pedrobaeza says is first addons from odoo and after other addons. My answer old is incorrect.

**Comment by SalahAdDin** [comment]
Is it mandatory in the configuration files?
Because documentation does not say anything about that, inclusive in the docker documentation, we just need to add our custom paths.

**Comment by pedrobaeza** [comment]
I don't understand why are you so insistent. Just do it. I'm not going to answer more replies.

**Comment by SalahAdDin** [comment]
I did it and it brings me other problem:
```
2018-07-12 06:04:05,002 986 WARNING ? odoo.service.server: LongPolling virtual memory limit reached: 813498368
2018-07-12 06:04:38,107 997 WARNING ? odoo.service.server: LongPolling virtual memory limit reached: 813617152
```

If I add that folders: `odoo` addons path and `crm` path I get constantly that problem.
problema

So, i delete that paths and i don't get any problem:
nada

it is a memory consumption problem, i think it could be because a circular importing or some like that.

But why?

**Pull request closed without merging**
