### PR TITLE
[12.0][MIG] crm_claim: Migration to v12

### PR DESCRIPTION
**Pull request by cristinamartinrod**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Squash adjacent translation and POT commits

**Comment by MiquelRForgeFlow** [comment]
The PR is repeated. See https://github.com/OCA/crm/pull/242.

**Comment by pedrobaeza** [comment]
This is the good one.

**Review by anandkansagra — APPROVED** [review]

**Review by anandkansagra — COMMENTED** [review]
Travis seems failed

**Comment by anandkansagra** [comment]
Code migration is LGTM

**Comment by pedrobaeza** [comment]
@cristinamartinrod please fix Travis

**Comment by pedrobaeza** [comment]
@cristinamartinrod please include #259

**Comment by anajuaristi** [comment]
functional test OK for this PR
:+1:

**Comment by anajuaristi** [comment]
Could it be merged??? Thanks

**Review by oihane — APPROVED** [review]
LGTM, only missing what @pedrobaeza told to change

**Review by DarioLodeiros — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The `default` type is already fixed, so I merge.

**Comment by anajuaristi** [comment]
GRACIAS a todos!!! Y una más que ya tenemos en V12.
Sois la leche.
:)

**Pull request merged**
