### PR TITLE
[MIG] crm_claim_code: Migration to 14.0

### PR DESCRIPTION
**Pull request by Reyes4711-S73**
Standard migration to 14.0
Depends on https://github.com/OCA/crm/pull/370

### CODE REVIEW

**Comment by oihane** [comment]
@Reyes4711 can you please rebase? crm_claim is already merged to v14.0.

**Comment by Reyes4711-S73** [comment]
@oihane Rebased.

**Review by Daniel-CA — APPROVED** [review]
LGTM

**Review by oihane — APPROVED** [review]
LGTM

We are using it, no error found

**Comment by Daniel-CA** [comment]
Can this one be merged?

**Pull request merged**
