### PR TITLE
Translated using Poedit

### PR DESCRIPTION
**Pull request by bigfoot88**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
Please do the translations through the weblate platform:
https://odoo-community.org/page/translate

Note. Via weblate it is also possible to import the translation generated via POEdit

**Comment by bigfoot88** [comment]
Ok.Let me try it.

**Comment by bigfoot88** [comment]
> Please do the translations through the weblate platform:
> https://odoo-community.org/page/translate
> 
> Note. Via weblate it is also possible to import the translation generated via POEdit

image
Hi,Could you please tell me why I don't have permission to start a new translation.

**Comment by pedrobaeza** [comment]
You have to ask for it at the mentioned email in the provided link.

**Comment by marcelsavegnago** [comment]
@bigfoot88 
image

**Comment by bigfoot88** [comment]
I see,thx

**Pull request closed without merging**
