### PR TITLE
[17.0][MIG] crm_lead_firstname: Migration to 17.0

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Comment by cormaza** [comment]
@celm1990 please can you follow instructions to reduce commits to review

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Review by cormaza — APPROVED** [review]
LGTM

**Comment by celm1990** [comment]
@OCA/crm-sales-marketing-maintainers could someone help me keep this PR open?

**Comment by celm1990** [comment]
This PR has been waiting for a long time. Can someone help me? Ping @OCA/crm-sales-marketing-maintainers.
CC: @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
