### PR TITLE
[13][FIX] Add activities in chatter

### PR DESCRIPTION
**Pull request by flachica**
With this fix you can plan activities

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
LGTM

I'll make a fast-tracking for non blocking this.

**Comment by bodedra** [comment]
@flachica @HaraldPanten I don't see form view for Phone Calls.

Screenshot from 2020-12-22 09-22-31

Or Am I missing something?

**Comment by skeller1** [comment]
> @flachica @HaraldPanten I don't see form view for Phone Calls.
> 
> Screenshot from 2020-12-22 09-22-31
> 
> Or Am I missing something?

Activate form view in crm settings (Enable form view for phone calls)

**Comment by bodedra** [comment]
@skeller1 Now it makes sense. Thanks for your response.

**Pull request merged**
