### PR TITLE
[14.0][mig] crm_stage_probability

### PR DESCRIPTION
**Pull request by robin5210**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@robin5210 Thanks for this. FYI, you can use readme fragments as in https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

**Comment by robin5210** [comment]
I have added the readme fragments and manually generated the main readme file trough the oca maintainer tools readme gen.

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by clementmbr — APPROVED** [review]
LGTM

**Comment by clementmbr** [comment]
Hi @robin5210, this PR is not merged only because of its red codecov ? Or is it because it needs more reviewers ?
Thanks!

**Pull request merged**
