### PR TITLE
[11.0][MIG] crm_deduplicate_filter

### PR DESCRIPTION
**Pull request by ernestotejeda**
Depends on:

- [x] crm_deduplicate_acl - #187 

cc @Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
cc @Tecnativa

**Comment by rafaelbn** [comment]
@ernestotejeda please could you rebase? Dependency is already merged, thanks

cc @Tecnativa

**Comment by DarioLodeiros** [comment]
@pedrobaeza Can you rebase? Thanks!

**Comment by pedrobaeza** [comment]
Done, you can review as soon as the build is ready.

**Review by DarioLodeiros — APPROVED** [review]
:+1: 
Code and Tests Review

**Pull request merged**
