### PR TITLE
[FIX] crm_project_task: Error when create task

### PR DESCRIPTION
**Pull request by EmilioPascual**
Error when you try to create the task from a lead/opportunity when you come from the contact

@moduon MT-4999

@edlopen @fcvalgar @Shide @yajo @rafaelbn please review if you want.

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review, 

LGTM, thank you @EmilioPascual.

https://www.loom.com/share/1e683a1befc04266bce9a99a33486361?sid=37345d20-7352-45cb-a043-b3c39adb90ae

**Comment by EmilioPascual** [comment]
Fix error creating task from lead/opportunity when accessing lead/opportunity from contact
https://www.loom.com/share/3884ff454f3a4916979b03495582f86f?sid=c9c3739f-41c6-402e-b2c6-dbad6b70d0b7

**Review by rafaelbn — APPROVED** [review]
Seen. OK 👍🏼 thank you!

**Pull request merged**
