### PR TITLE
[ADD] crm_industry: Propagate industries from customer to lead/opportunity

### PR DESCRIPTION
**Pull request by mamcode**
This PR adds onchange event over field partner_id in leads to pull the industries from customer's contact to the lead

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @fcvalgar @Luisotto could you please review?

**Review by rafaelbn — APPROVED** [review]
Functional review in runbot 👍 

imagen

**Comment by fcvalgar** [comment]
Functional review in runbot +1

**Review by ghost — APPROVED** [review]
Checked! LGTM!

**Review by fcvalgar — APPROVED** [review]
Functional review in runbot +1

**Pull request merged**
