### PR TITLE
[IMP] crm_claim_code: changed default set way in order to allow module extensions

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: if :green_heart:

**Comment by oihane** [comment]
This is the module that requires the change: https://github.com/avanzosc/odoo-addons/pull/278

**Comment by esthermm** [comment]
LGTM :+1:

**Comment by anajuaristi** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Pull request merged**
