### PR TITLE
[12.0] remove unicodecsv from .travis.yml

### PR DESCRIPTION
**Pull request by yucer**
I find no import of unicodecsv in the addons of this repo.

### CODE REVIEW

**Review by skeller1 — APPROVED** [review]
already removed from .travis.yml in 13.0 branch
:+1: LGTM

**Comment by rousseldenis** [comment]
@yucer Could you please include also some entries following this : https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

Don't take all the pre-commit stuff (for >= v13), but at least remove transifex entries and add makepot ones(we moved from transifex to weblate).

**Comment by yucer** [comment]
> @yucer Could you please include also some entries following this : https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml
> 
> Don't take all the pre-commit stuff (for >= v13), but at least remove transifex entries and add makepot ones(we moved from transifex to weblate).

@rousseldenis , Actually, I am not "fit" with the *travis* configurations in OCA repos. I wish I do, so I can collaborate more, but we use internal gitlab + another CI and I am outdated.

I have done dependency removal, because I found one case in another repo and later made a query all over the repositories to see which was in the same situation.

Maybe anybody else can do what you need ? And please tag me when solved in order to learn.

**Comment by rousseldenis** [comment]
> > @yucer Could you please include also some entries following this : https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml
> > Don't take all the pre-commit stuff (for >= v13), but at least remove transifex entries and add makepot ones(we moved from transifex to weblate).
> 
> @rousseldenis , Actually, I am not "fit" with the _travis_ configurations in OCA repos. I wish I do, so I can collaborate more, but we use internal gitlab + another CI and I am outdated.
> 
> I have done dependency removal, because I found one case in another repo and later made a query all over the repositories to see which was in the same situation.
> 
> Maybe anybody else can do what you need ? And please tag me when solved in order to learn.

Ok, we can do this and then I'll do the other entries.

**Pull request closed without merging**
