### PR TITLE
15.0 mig crm lead firstname

### PR DESCRIPTION
**Pull request by Galoperd**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! It seems that this module's tests are failing. Can you have a look?

**Comment by Galoperd** [comment]
Not sure how to correct, please help:
```
2022-09-03 07:40:57,298 254 ERROR odoo odoo.addons.crm_lead_firstname.tests.test_crm_lead: ERROR: FirstNameCase.test_create_contact
Traceback (most recent call last):
  File "/__w/crm/crm/crm_lead_firstname/tests/test_crm_lead.py", line 28, in test_create_contact
    self.lead.handle_partner_assignment()
AttributeError: 'crm.lead' object has no attribute 'handle_partner_assignment'
```

**Comment by StefanRijnhart** [comment]
@Galoperd well, if you want to migrate a module you have to read all the code and check the upstream Odoo entry points that it uses and check if the upstream Odoo API has changed. Please check what happened to the `handle_partner_assignment` method in core Odoo.

**Comment by StefanRijnhart** [comment]
Superseded by https://github.com/OCA/crm/pull/441

**Pull request closed without merging**
