### PR TITLE
[15.0][IMP] crm_salesperson_planner: Refactoring of the template to make it usable and with simplified code

### PR DESCRIPTION
**Pull request by victoralmau**
Refactoring of the template to make it usable and with simplified code.

@Tecnativa TT48238

### CODE REVIEW

**Comment by victoralmau** [comment]
IMO I think you have to remove the `calendar.event` inheritance in templates. It adds "_nothing_", `write()` method is overwritten, and this https://github.com/odoo/odoo/blob/15.0/addons/calendar/models/calendar_event.py#L489 causes problems. 

What do you think @pedrobaeza ?

**Comment by pedrobaeza** [comment]
I can't say right now, Víctor. I need also steps to reproduce the problem this is fixing, and also a regression test would be advisable.

**Comment by victoralmau** [comment]
> I can't say right now, Víctor. I need also steps to reproduce the problem this is fixing, and also a regression test would be advisable.

Sorry, a small change has been added to see the error https://github.com/OCA/crm/actions/runs/8229098690/job/22499657123?pr=558#step:8:258

Steps to reproduce the error:
- Delete all `calendar.event` records
- Try to create a template.

There is a lot of logic inside `calendar.event` and I think that in the template inheriting from calendar.event doesn't add anything now.

**Comment by victoralmau** [comment]
Ping @pedrobaeza

**Comment by pedrobaeza** [comment]
OK, I see. Yes, I agree on removing the inherit in `crm.salesperson.planner.visit.template`.

**Comment by victoralmau** [comment]
All the changes are already done for everything works as expected, simplified the code and added more tests with specific use cases.

Can you check that the operation is correct? Ping @sergio-teruel

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
